export const CodigoDeErro = {
  REQUISICAO_INVALIDA: "REQUISICAO_INVALIDA",
  ERRO_DE_VALIDACAO: "ERRO_DE_VALIDACAO",
  NAO_AUTORIZADO: "NAO_AUTORIZADO",
  PROIBIDO: "PROIBIDO",
  NAO_ENCONTRADO: "NAO_ENCONTRADO",
  CONFLITO: "CONFLITO",
  NAO_IMPLEMENTADO: "NAO_IMPLEMENTADO",
  ERRO_INTERNO: "ERRO_INTERNO",
} as const;

export type ValorCodigoDeErro = (typeof CodigoDeErro)[keyof typeof CodigoDeErro];
