module.exports = {
  clearMocks: true,
  collectCoverageFrom: [
    "src/config/cors.ts",
    "src/config/env.ts",
    "src/modules/auth/aluno/aluno.controller.ts",
    "src/modules/auth/aluno/aluno.repository.ts",
    "src/modules/auth/aluno/aluno.schemas.ts",
    "src/modules/auth/aluno/aluno.service.ts",
    "src/modules/auth/aluno/dto/resposta.aluno.types.ts",
    "src/modules/auth/aluno/localidades/localidades.controller.ts",
    "src/modules/auth/aluno/localidades/localidades.schemas.ts",
    "src/modules/auth/aluno/localidades/localidades.service.ts",
    "src/modules/auth/aluno/nacionalidades/nacionalidades.controller.ts",
    "src/modules/auth/aluno/nacionalidades/nacionalidades.service.ts",
    "src/modules/auth/aluno/opcoes-academicas/opcoes-academicas.controller.ts",
    "src/modules/auth/aluno/opcoes-academicas/opcoes-academicas.service.ts",
    "src/shared/middlewares/autenticacao.middleware.ts",
    "src/shared/middlewares/validacao.middleware.ts",
    "src/shared/utils/formatacao.util.ts",
    "src/shared/utils/jwt.ts",
    "src/shared/utils/paginacao.util.ts",
  ],
  coverageReporters: ["text", "lcov", "json-summary"],
  moduleFileExtensions: ["ts", "js", "json"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/src/$1",
  },
  setupFiles: ["<rootDir>/jest.setup.js"],
  testEnvironment: "node",
  testMatch: ["<rootDir>/src/**/*.test.ts", "<rootDir>/tests/**/*.test.ts"],
  transform: {
    "^.+\\.ts$": "babel-jest",
  },
};
