export const MENSAGENS = {
  apiEmExecucao: "API do AnatoQuizUp em execucao.",
  erroInterno: "Ocorreu um erro interno inesperado.",
  erroValidacao: "Falha na validacao da requisicao.",
  rotaNaoEncontrada: "A rota solicitada nao foi encontrada.",
  exemploCriado: "Exemplo criado com sucesso.",
  exemploNaoEncontrado: "Exemplo nao encontrado.",
  exemploEncontrado: "Exemplo encontrado com sucesso.",
  usuarioCadastrado: "Usuario cadastrado com sucesso.",
  emailJaCadastrado: "Ja existe um usuario cadastrado com este email.",
  nicknameJaCadastrado: "Ja existe um usuario cadastrado com este nickname.",
  nacionalidadesListadas: "Nacionalidades listadas com sucesso.",
  opcoesAcademicasListadas: "Opcoes academicas listadas com sucesso.",
  emailDisponivel: "Email disponivel para uso.",
  nicknameDisponivel: "Nickname disponivel para uso.",
  instrucoesRecuperacaoSenhaEnviadas:
    "Se o email existir no sistema, enviamos instrucoes.",
  senhaRedefinida: "Senha redefinida com sucesso.",
  linkRedefinicaoSenhaInvalido: "Link expirado ou invalido.",
  estadosListados: "Estados listados com sucesso.",
  cidadesListadas: "Cidades listadas com sucesso.",
  origemCorsNaoPermitida: "Origem nao permitida pelo CORS.",
  autenticacaoNaoImplementada: "O middleware de autenticacao ainda nao foi implementado.",
  permissaoPorPapelNaoImplementada:
    "O middleware de permissao por papel ainda nao foi implementado.",
} as const;
