export const MENSAGENS = {
  apiEmExecucao: "API do AnatoQuizUp em execucao.",
  erroInterno: "Ocorreu um erro interno inesperado.",
  erroValidacao: "Falha na validacao da requisicao.",
  rotaNaoEncontrada: "A rota solicitada nao foi encontrada.",
  exemploCriado: "Exemplo criado com sucesso.",
  exemploNaoEncontrado: "Exemplo nao encontrado.",
  exemploEncontrado: "Exemplo encontrado com sucesso.",
  usuarioCadastrado: "Usuario cadastrado com sucesso.",
  emailJaCadastrado: "Ja existe um usuario cadastrado com este email.",
  nicknameJaCadastrado: "Ja existe um usuario cadastrado com este nickname.",
  nacionalidadesListadas: "Nacionalidades listadas com sucesso.",
  opcoesAcademicasListadas: "Opcoes academicas listadas com sucesso.",
  emailDisponivel: "Email disponivel para uso.",
  nicknameDisponivel: "Nickname disponivel para uso.",
  estadosListados: "Estados listados com sucesso.",
  cidadesListadas: "Cidades listadas com sucesso.",
  origemCorsNaoPermitida: "Origem nao permitida pelo CORS.",
  loginRealizado: "Login realizado com sucesso.",
  sessaoRenovada: "Sessao renovada com sucesso.",
  usuarioAutenticadoEncontrado: "Usuario autenticado retornado com sucesso.",
  credenciaisInvalidas: "Email ou senha invalidos.",
  tokenInvalido: "Token invalido.",
  cadastroEmAnalise: "Seu cadastro esta em analise pelo administrador.",
  contaDesativada: "Conta desativada. Entre em contato com o administrador.",
  cadastroRecusado: "Cadastro recusado. Entre em contato com o administrador.",
  autenticacaoNaoImplementada: "O middleware de autenticacao ainda nao foi implementado.",
  permissaoPorPapelNaoImplementada:
    "O middleware de permissao por papel ainda nao foi implementado.",
} as const;
